version: "3.9"
services:
  frontend:
    container_name: frontend
    ports:
      - "3000:3000"
    build:
      context: ./packages 
      dockerfile: Dockerfile.frontend
    volumes:
      - ./packages/frontend:/frontend
      - /frontend/node_modules
      - /frontend/.next
